### ISSUE TITLE
Invalid query format for variant

### ISSUE THREAD

**Issue by aeclmic** [timyers/ldlinkr#1] opened 2019-08-22 12:14 UTC
Hello,

Recently I was pointed to your package, which I greatly appreciate. Unfortunately I've run into an issue:

I have SNP data in the format "chr"CHROM:POS, with positions ranging from 7 to 9 digits. 
My data is from an imputation server that uses Genome Build 37.

However, LDlinkR only accepts positions of exactly 8 digits. What is the reason for that? 

Furthermore, when appending the 7-digit positions with a 0 in front, I get no results either (example: _"error: chr10:09062856 is not in dbSNP build 151."_)

Thank you in advance.

**Comment by timyers** [comment] 2019-08-22 15:51
Hello,

Thank you for your interest in LDlinkR and for letting us know about this issue.  It's being caused by something I overlooked regarding the regular expression that defines chromosome coordinates.  I'll begin working on a fix immediately.

Thanks again for letting us know about it.

**Comment by timyers** [comment] 2019-09-25 18:53
This issue has been fixed on GitHub.  Until the next version is released, the workaround is to install from github with devtools.

devtools::install_github("CBIIT/LDlinkR")

**Comment by timyers** [comment] 2019-10-21 12:35
This issued has been resolved with a patch fix that has been uploaded to CRAN.

**Closed as completed by timyers** 2019-10-21 12:35 UTC
Labels: invalid
